#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethserver-subscription-update event
#

my $event = 'nethserver-subscription-update';

event_actions($event, qw(
      initialize-default-databases 00
));

event_templates($event, qw(
    /etc/yum.repos.d/subscription.repo
    /etc/yum/vars/nsrelease
));

#
# nethserver-subscription-save event
#

$event = 'nethserver-subscription-save';

event_actions($event, qw(
      nethserver-subscription-yum-cleanall 20
      nethserver-subscription-register 20 
      nethserver-subscription-eorepo 30
));

event_templates($event, qw(
    /etc/yum.repos.d/subscription.repo
));
