#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethserver-subscription-update event
#

event_templates('nethserver-subscription-update', qw(
    /etc/yum.repos.d/subscription.repo
    /etc/yum/vars/nsrelease
    /etc/sysconfig/run-parts
    /etc/collectd.d/threshold.conf
    /etc/collectd.d/filter.conf
    /etc/collectd.d/ping.conf
));

event_actions('nethserver-subscription-update', qw(
      initialize-default-databases 00
));

event_services('nethserver-subscription-update', qw(
    collectd restart
));

#
# nethserver-subscription-save event
#

event_actions('nethserver-subscription-save', qw(
      nethserver-subscription-eorepo 30
      nethserver-inventory-send 30
));

event_templates('nethserver-subscription-save', qw(
    /etc/yum.repos.d/subscription.repo
    /etc/yum/vars/nsrelease
    /etc/sysconfig/run-parts
    /etc/collectd.d/threshold.conf
));

event_services('nethserver-subscription-save', qw(
    collectd restart
));


#
# nethserver-backup-data-update event
#

event_templates('nethserver-backup-data-update', qw(
   /etc/collectd.d/threshold.conf
   /etc/collectd.d/filter.conf
));


#
# nethserver-collectd-save event
#

event_templates('nethserver-collectd-save', qw(
  /etc/collectd.d/threshold.conf
  /etc/collectd.d/filter.conf
));

#
# nethserver-collectd-update event
#

event_templates('nethserver-collectd-update', qw(
  /etc/collectd.d/threshold.conf
  /etc/collectd.d/filter.conf
));


#
# interface-update event
#

event_actions('interface-update', qw(
    nethserver-alerts-reset-wan   03
));

#
# wan-uplink-update event
#

event_actions('wan-uplink-update', qw(
    nethserver-alerts-lsm-update 60
));

#
# nethserver-alerts-save event
#

event_templates('nethserver-alerts-save', qw(
   /etc/collectd.d/threshold.conf
   /etc/collectd.d/filter.conf
   /etc/collectd.d/ping.conf
));

event_actions('nethserver-alerts-save', qw(
    nethserver-alerts-update-alertsdb   02
));

event_services('nethserver-alerts-save', qw(
    collectd restart
));


#
# pre-restore-config event
#
event_actions('pre-restore-config', qw(
    nethserver-subscription-restore-yumrepos 20
));

#
# software-repos-save event
#
event_templates('software-repos-save', qw(
    /etc/yum.repos.d/subscription.repo
));

#
# post-restore-data event
#
event_actions('post-restore-data', qw(
    nethserver-inventory-send 95
));
