#!/bin/bash

# Download alerts configuration from remote server
# if subscription[AlertsAutoUpdates] is enabled

status=$(/sbin/e-smith/config getprop subscription AlertsAutoUpdates)

if [ "$status" == "enabled" ]; then
    /sbin/e-smith/signal-event nethserver-alerts-save
fi
