#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# NethServer Subscription
#

event=$1
systemId=$(/sbin/e-smith/config getprop subscription SystemId)
if [[ -z ${systemId} ]]; then
    exit 0
fi

# Override default repositories with eorepo.conf
eorepo_cfg=/etc/nethserver/eorepo.conf
if [[ -r ${eorepo_cfg} ]]; then
    repositories=($(grep -vE '^#' ${eorepo_cfg}))
fi

if [[ ${#repositories[@]} -eq 0 ]]; then
    repositories=(
        sb-base
        sb-updates
        sb-epel
        sb-extras
        sb-centos-sclo-rh
        sb-centos-sclo-sclo
        sb-nethserver-base
        sb-nethserver-updates
    )
fi

echo "[NOTICE] eorepo ${repositories[*]}"
exec /sbin/e-smith/eorepo ${repositories[*]}
