#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Extract the configuration DB from backup to a temporary dir, and use it 
# to restore the yum repositories configuration
#

tmpdir=$(mktemp -d /tmp/restore-yumrepos.XXXXXXX)
trap "rm -rf ${tmpdir}" EXIT

tar -x -C "${tmpdir}" -f /var/lib/nethserver/backup/backup-config.tar.xz  var/lib/nethserver/db/configuration

export ESMITH_CONFIG_DB="${tmpdir}/var/lib/nethserver/db/configuration"

if [[ -z $(/sbin/e-smith/config getprop subscription SystemId) ]]; then
    exit 0;
fi

echo "[NOTICE] This system has a subscription. Restoring YUM repository configuration"
/sbin/e-smith/signal-event restore-yumrepos

