#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Retrieve customized alerts configuration

SYSTEMID=$(/sbin/e-smith/config getprop subscription SystemId)
URL=$(/sbin/e-smith/config getprop subscription AlertsUrl)

ALERTSDBJSON=$(/usr/bin/curl -s "https://$URL/customalerts/configuration?system_key=$SYSTEMID")
RES1=$?

if [[ $RES1 == 0 ]] ; then
    # create temp db file
    TMPDB=$(mktemp)
    /sbin/e-smith/db $TMPDB setjson "$ALERTSDBJSON"
    RES2=$?

    # compare temp db file with alerts db
    if [[ $(/sbin/e-smith/db $TMPDB show | md5sum) != $(/sbin/e-smith/db alerts show | md5sum) ]] ; then
        # temp db differs from alerts db
        mv $TMPDB /var/lib/nethserver/db/alerts
    else
        # db isn't changed
        rm $TMPDB
    fi
    if [ -f /var/lib/nethserver/db/alerts ]; then
        /usr/bin/chown root:adm /var/lib/nethserver/db/alerts
    fi
fi

if [[ $RES1 == 0 && $RES2 == 0 ]]; then
    exit 0
else
    exit 1
fi
