#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Retrieve customized alerts configuration

SYSTEMID=$(/sbin/e-smith/config getprop subscription SystemId)
URL=$(/sbin/e-smith/config getprop subscription AlertsUrl)

TMPJSON=$(mktemp --tmpdir alerts-XXXXXXX.json)
TMPDB=$(mktemp --tmpdir alerts-XXXXXXX.db)

trap "rm -f ${TMPJSON} ${TMPDB}" EXIT

curl -s "${URL}/customalerts/configuration?system_key=$SYSTEMID" > ${TMPJSON}
if [[ $? != 0 ]]; then
    echo "[ERROR] customalerts remote HTTP call failed"
    exit 1
fi

/sbin/e-smith/db $TMPDB setjson - <${TMPJSON}
if [[ $? != 0 ]]; then
    echo "[ERROR] failed to load custom alerts database"
    exit 1
fi

chown root:adm ${TMPDB}
chmod 644 ${TMPDB}

# compare temp db file with alerts db to avoid backup-config unnecessary runs
if [[ $(/sbin/e-smith/db $TMPDB show | md5sum) != $(/sbin/e-smith/db alerts show | md5sum) ]] ; then
    # temp db differs from alerts db
    echo "[NOTICE] commit alerts DB differences"
    mv ${TMPDB} /var/lib/nethserver/db/alerts
fi
