#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# NethServer Subscription
#

event=$1
systemId=$(/sbin/e-smith/config getprop subscription SystemId)
if [[ -z ${systemId} ]]; then
    exit 0
fi

# Make sure NsReleaseLock is disabled
/sbin/e-smith/config setprop sysconfig NsReleaseLock disabled

echo "[NOTICE] This system is subscribed as ${systemId}. Fixing YUM repository configuration"
/sbin/e-smith/signal-event software-repos-save
