#!/bin/bash
#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer Enterprise
# All rights are reserved
#

# Skip event name
shift;

STATE=${1}
NAME=${2}
PREVSTATE=${15}
TIMESTAMP=${16}

hostname=$(hostname)
severity=""

if [ ${STATE} = ${PREVSTATE} ]; then
    exit 0
fi

if [ ${STATE} = up ]; then
  severity="okay"
else
  severity="failure"
fi

# reset only when state move from unknow to down to avoid false reset.
# if an up state comes after a down state (for each wan), all alerts will be erased.
# check only the down state to trigger failed status
if [ ${PREVSTATE} = 'unknown' ] && [ ${STATE} = 'down' ] ; then
    echo -e "PUTNOTIF host=$hostname plugin=wan plugin_instance=wan_reset type=down severity=failure time=$TIMESTAMP message=\"$NAME is $STATE\"\n" | nc -U /var/run/collectd.sock &>/dev/null
fi

echo -e "PUTNOTIF host=$hostname plugin=wan plugin_instance=$NAME type=down severity=$severity time=$TIMESTAMP message=\"$NAME is $STATE\"\n" | nc -U /var/run/collectd.sock &>/dev/null

exit 0;
